@startuml usecase
    actor "Client principal" as clientStart
    actor "Client secondaire" as clientJoin
    package Application{
        rectangle "Connexion au site internet" as connexion
        clientStart --> connexion
        clientJoin --> connexion
        rectangle "Affichage menu" as menu
        connexion --> menu
        rectangle "Rejoindre la partie" as rejoindre
        menu --> rejoindre
        rectangle "Lancer la partie" as lancer
        menu --> lancer
        rectangle "Génération lien de partie" as lien
        lancer --> lien

        rectangle "Déplacer joueur" as deplacement
        lien --> deplacement
        rejoindre --> deplacement

    }


@enduml